version: 0.0
os: linux
files:
  - source: .
    destination: /usr/local/codedeployresources
hooks:
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 300
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
  ValidateService:
    - location: scripts/validate-service.sh
      timeout: 300
