# This is a basic workflow that is manually triggered

name: UAT Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      archivename:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Artifact to deploy'
        # Default value if no value is explicitly provided
        default: 'artifact-1.zip'
        # Input has to be provided for the workflow to run
        required: true
env:
  AWS_REGION: us-east-1
  appname: GitDeployApp
  deploy-group: GitDeployGroup
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      # # Create deployment to CodeDeploy
      - name: AWS Create Deployment
        run: |
          aws deploy create-deployment \
           --application-name ${{ env.appname }} \
           --deployment-config-name CodeDeployDefault.AllAtOnce \
           --deployment-group-name ${{ env.deploy-group }} \
           --file-exists-behavior OVERWRITE \
           --s3-location bucket=${{ secrets.AWS_BUCKET }},key=${{ github.event.inputs.archivename }},bundleType=zip \
           --description "Deployment for ${{ env.appname }}-${{ github.sha }}"
